name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: Is your feature request related to a problem? Please describe what you're trying to achieve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Any other approaches that might work...

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe how this feature would be used and who would benefit from it.
      placeholder: This would help developers who...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information...