name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create GitHub release
        run: gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --notes "$(npx changelogen --no-output)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}